/**
 * Curated memorable wordlist for passphrase generation.
 * 512 simple, distinct, easy-to-visualise English words (~9 bits entropy each).
 * Chosen to be: 3-7 letters, kid-friendly, no homophones, no offensive terms,
 * no extreme ambiguity with digits/symbols. Inspired by the EFF approach but
 * trimmed for offline use without bundling the full 7776-word Diceware list.
 *
 * With N words chosen uniformly at random, entropy ≈ N × log2(512) = N × 9 bits.
 * 5 words → 45 bits · 6 words → 54 bits · 7 words → 63 bits · 8 words → 72 bits.
 */

export const MEMORABLE_WORDS: readonly string[] = [
  "apple","arctic","arrow","ashen","atlas","azure","badge","bamboo","banner","basin",
  "beacon","beagle","berry","bison","blade","blossom","bluebird","bobcat","bolt","bracket",
  "bramble","bravo","breeze","brick","bronze","broom","bubble","buckle","buffer","bugle",
  "butter","button","cactus","camel","camp","candle","canopy","canvas","carbon","cargo",
  "cascade","castle","cedar","chalk","champion","chant","chapel","cheese","cherry","chest",
  "chimney","chrome","cipher","citrus","civic","clamor","clarity","claw","cleat","cliff",
  "clockwork","clove","cobalt","cocoa","comet","compass","copper","coral","cosmos","cotton",
  "cougar","crayon","crocus","crystal","cube","cumin","curtain","cushion","cyclone","daisy",
  "dart","delta","denim","depth","desert","dewdrop","digger","dimple","dinner","dipper",
  "dolphin","donor","dot","dove","drift","dune","dynamo","eagle","earth","echo",
  "edge","ember","emerald","engine","epoch","ermine","escape","estate","ether","evening",
  "fable","falcon","feather","ferret","festival","fiddle","fjord","flag","flame","flax",
  "flicker","flint","floral","flutter","foam","foggy","forest","fort","foxglove","fragrant",
  "frantic","frost","fuchsia","gadget","galaxy","gallant","garden","garlic","gentle","gesture",
  "ghost","ginger","glacier","glade","glimmer","glockenspiel","glossy","glow","goblin","golden",
  "goose","gourmet","gracious","granite","grape","grasshopper","gravity","green","grouse","guppy",
  "gust","gypsy","halcyon","halo","hammer","harbor","harmony","haste","hazel","hearth",
  "heather","helmet","heron","highland","honeydew","horizon","horse","huckleberry","hurdle","hyacinth",
  "iceberg","indigo","inkwell","ivory","ivy","jacket","jade","jaguar","jasmine","jester",
  "jet","jingle","jovial","joyful","jubilee","judge","jumbo","juniper","kaleidoscope","kayak",
  "kelp","kestrel","kettle","keyboard","kingship","kismet","kitten","knight","lacquer","lagoon",
  "lakeside","lantern","laurel","lavender","leaf","lemon","leopard","lighthouse","lilac","lime",
  "limestone","linear","lion","liver","llama","lobster","lock","lodge","lotus","luminous",
  "lunar","lupine","luster","lyric","magenta","magnolia","majestic","mango","manor","maple",
  "marble","marigold","marsh","mason","meadow","medal","melon","mercury","merry","metal",
  "meteor","mica","midnight","mimosa","mink","minuet","mirror","misty","mocha","monarch",
  "mongoose","monsoon","moonlight","morning","mosaic","moss","moth","motor","mountain","muffin",
  "musing","mustard","myriad","mystic","nectar","nebula","neon","nephew","nestle","network",
  "newt","nimbus","noble","nod","nomad","noon","northern","notebook","nougat","november",
  "nucleus","nugget","nursery","nurse","nursling","oasis","oat","ocean","octave","octopus",
  "onyx","opal","opera","optical","orange","orchard","orchid","oriole","otter","ounce",
  "outback","oval","overture","owl","oxen","oxygen","oyster","pacific","paddle","pagoda",
  "palace","panda","pantry","papaya","parade","parcel","parfait","parrot","parsley","partridge",
  "passage","pastel","patch","patio","paul","pause","pavilion","peacock","peanut","pearl",
  "pebble","pedal","pelican","pencil","peony","pepper","perfume","petal","phantom","phoenix",
  "phone","picnic","pilot","pine","pioneer","pistachio","piston","pith","pizza","placid",
  "planet","plank","platinum","plaza","pleasure","plum","plume","pluto","poem","polar",
  "polish","polite","pollen","polo","pomelo","pomegranate","pond","poppy","porcelain","portal",
  "poster","pottery","prairie","prawn","prelude","present","pretzel","prince","prism","profit",
  "prosper","proton","puffin","pumpkin","punch","pupil","puppy","purse","quail","quartz",
  "quasar","quaver","quench","querent","quest","quibble","quick","quill","quilt","quince",
  "quirky","quiver","quiz","quokka","quota","quote","rabbits","raccoon","radar","radish",
  "raft","ragoon","rainbow","ranger","rapids","raven","reactor","rebel","recipe","redwood",
  "reef","regatta","relish","remark","renew","resin","ribbon","riddle","ridge","rifle",
  "ring","ripple","river","road","robin","robot","rock","rocket","rodent","rogue",
  "rolling","rooster","rose","roster","ruby","ruler","runway","russet","sable","saffron",
  "sage","sail","salamander","salmon","salon","saloon","salt","samba","sandbox","sandal",
  "sapphire","satellite","satin","sauce","savage","saxophone","scallion","scarf","scarlet","scholar",
  "scoop","scout","sculpture","seashell","season","secret","seedling","seismic","select","senate",
  "senior","serene","series","serpent","service","sesame","shadow","shamrock","shield","shift",
  "ship","shore","shoulder","shovel","shower","shrine","sienna","silk","silver","simmer",
  "sincere","singer","single","siren","sister","sketch","skewer","ski","skiff","skillet",
  "skylark","skyline","slate","sledge","sleepy","sleuth","slinky","slow","smile","smoke",
  "smooth","snail","snake","snapshot","sneaker","snow","snowman","snuggle","soap","soaring",
  "sober","soccer","socket","soft","solar","solo","sonar","sonata","songbird","sonic",
  "soothe","sorbet","sound","southern","sovereign","sparkle","sparrow","spear","spectacle","speed",
  "spell","sphere","spice","spider","spike","spinach","spiral","spirit","sponge","spoon",
  "spore","sport","spotlight","spruce","squad","squirrel","stable","stack","stadium","staff",
  "stage","staircase","stallion","stamina","stamp","stanza","star","starch","stargazer","station",
  "steady","steam","steel","steeple","stellar","stem","stencil","step","stew","sticky",
  "stilt","stingray","stitch","stone","stopwatch","storm","stout","stove","straw","stream",
  "street","stride","string","stripes","studio","study","stunt","suave","subject","submit",
  "subway","success","sudden","sugar","suit","sultry","summer","sun","sunbeam","sundial",
  "sunglasses","sunny","sunrise","sunset","sunshine","super","sushi","swallow","swamp","swan",
  "swap","sweater","sweep","sweet","swift","swim","swing","sycamore","synergy","syrup",
  "system","table","tackle","taco","tactic","tadpole","tail","talisman","tall","tamarind",
  "tangerine","tank","tapestry","tavern","teddy","tempo","tender","tenor","tent","tepee",
  "terrace","textile","thatch","theorem","thicket","thimble","thorn","thought","thread","throne",
  "throttle","thunder","tide","tiger","tilde","timber","timely","tin","tinsel","tip",
  "titan","title","toad","toast","toboggan","today","toggle","token","tomato","tonic",
  "topaz","topiary","topology","torch","tornado","torus","tote","towel","tower","town",
  "toxic","trace","track","trade","traffic","trail","tram","tranquil","transit","trapeze",
  "travel","tray","treat","treble","tree","trellis","trend","triangle","tribe","trinket",
  "triumph","trolley","trophy","trout","trumpet","trunk","trust","tutor","tuxedo","twilight",
  "twine","twins","twirl","twisty","tycoon","typist","udder","ultra","umber","umpire",
  "unblock","underdog","unicorn","uniform","union","unique","unison","universe","unleash","unruly",
  "upbeat","update","uphill","uplink","upon","upper","upright","upstairs","uptown","uranium",
  "urban","urgent","urging","usable","user","utensil","utility","vacuum","vague","valid",
  "valley","valor","vampire","vane","vapor","varied","vascular","vault","velvet","vendor",
  "verbose","verge","verify","verve","vessel","vest","veto","vex","viable","vibrant",
  "victory","video","viewer","village","vine","vinyl","viola","violet","violin","viper",
  "virtual","visa","visible","vision","visit","vital","vivid","vocal","vodka","voice",
  "volcano","volume","vortex","voter","voucher","voyage","waffle","wag","wagon","waist",
  "waking","walkway","walnut","waltz","wand","warrant","warrior","washer","water","wave",
  "wax","wayside","weaver","wedge","weekend","weight","weasel","welcome","wellness","whale",
  "wheat","wheel","whisper","whistle","white","wick","widget","willow","wind","window",
  "wine","wing","wink","winter","wire","wisdom","wise","wish","wisteria","wits",
  "wizard","wobble","wolf","wolverine","wonder","wood","wool","word","work","world",
  "worm","worst","worth","woven","wreath","wren","wrench","wrestle","wriggle","wrist",
  "writer","wrought","xylophone","yacht","yak","yam","yard","yarn","yearly","yellow",
  "yield","yodel","yogurt","young","youth","yoyo","zebra","zen","zest","zigzag",
  "zinc","zinnia","zip","zipper","zither","zodiac","zombie","zone","zoo","zoom",
] as const;

export const WORDLIST_SIZE = MEMORABLE_WORDS.length;
